[metadata]
format.version = "1.1"

[versions]
edc = "0.15.1"

[libraries]
# SPI modules
edc-spi-core = { module = "org.eclipse.edc:core-spi", version.ref = "edc" }
edc-spi-identity-trust = { module = "org.eclipse.edc:decentralized-claims-spi", version.ref = "edc" }
edc-spi-identity-did = { module = "org.eclipse.edc:identity-did-spi", version.ref = "edc" }
edc-spi-transform = { module = "org.eclipse.edc:transform-spi", version.ref = "edc" }
edc-spi-catalog = { module = "org.eclipse.edc:catalog-spi", version.ref = "edc" }

# IdentityHub SPI modules
edc-ih-spi = { module = "org.eclipse.edc:identity-hub-spi", version.ref = "edc" }
edc-ih-spi-credentials = { module = "org.eclipse.edc:verifiable-credential-spi", version.ref = "edc" }
edc-ih-spi-did = { module = "org.eclipse.edc:did-spi", version.ref = "edc" }

# Core modules
edc-did-core = { module = "org.eclipse.edc:identity-did-core", version.ref = "edc" }
edc-dcp-core = { module = "org.eclipse.edc:decentralized-claims-core", version.ref = "edc" }

# Lib modules
edc-lib-jws2020 = { module = "org.eclipse.edc:jws2020-lib", version.ref = "edc" }
edc-lib-transform = { module = "org.eclipse.edc:transform-lib", version.ref = "edc" }

# Vault
edc-vault-hashicorp = { module = "org.eclipse.edc:vault-hashicorp", version.ref = "edc" }
edc-participant-context-config-core = { module = "org.eclipse.edc:participant-context-config-core", version.ref = "edc" }
edc-participant-context-single-core = { module = "org.eclipse.edc:participant-context-single-core", version.ref = "edc" }

# BOM modules
edc-bom-controlplane = { module = "org.eclipse.edc:controlplane-dcp-bom", version.ref = "edc" }
edc-bom-dataplane = { module = "org.eclipse.edc:dataplane-base-bom", version.ref = "edc" }
edc-bom-controlplane-sql = { module = "org.eclipse.edc:controlplane-feature-sql-bom", version.ref = "edc" }
edc-bom-dataplane-sql = { module = "org.eclipse.edc:dataplane-feature-sql-bom", version.ref = "edc" }
edc-bom-identityhub = { module = "org.eclipse.edc:identityhub-bom", version.ref = "edc" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
docker = { id = "com.bmuschko.docker-remote-api", version = "9.4.0" }
